name: CI/CD AWS LifeCycle

on:
  push:
    paths:
      - 'lyfecycle/**'
      - '.github/workflows/lifecycle.yml'
    branches: [main]

jobs:
  build-test-upload:
    name: AWS LifeCycle
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          apt-get update && apt-get install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_REGION"

      - name: Run unit tests
        run: |
          pytest tests/

      - name: Execute main code (generates .sh file)
        run: |
          python main.py

      - name: Run generated AWS CLI script
        run: |
          chmod +x output/bash/lifecycle.sh
          ./output/bash/lifecycle.sh